### ISSUE TITLE
[BUG] SiliconCloud account not available with US number?

### ISSUE THREAD

**Issue by nexusjuan12** [siliconflow/BizyAir#101]
### Describe the Bug
I'd like to set my API key but I cannot seem to log into SiliconFlow using a US telephone number, is there a solution?
Error text or screenshot of the error.

### Steps to Reproduce

Please provide the workflow or steps to reproduce the bug.

### Environment

- **OS:** [e.g., Linux Ubuntu 12.04, Windows 10]
- **Browser:** [e.g., chrome, safari]

**Comment by doombeaker** [comment]
I am sorry for that the US number is not available NOW in siliconcloud.
but it will be available much likely in two weeks.

I will comment the updates here then.

**Comment by doombeaker** [comment]
@nexusjuan12 US phone number is available for signing in the siliconcloud, please try it again. please let us know if you encounter any issues.
