### ISSUE TITLE
[FEATURE REQUEST] could you give the seeds function to LLM node in BizyAir

### ISSUE THREAD

**Issue by jasoncow007** [siliconflow/BizyAir#114]
prompt always change at every queue, we need a normal llm note like others

**Comment by doombeaker** [comment]
ok，we can add a "no sample" option to this node.

**Comment by jasoncow007** [comment]
> ok，we can add a "no sample" option to this node.

and joy caption too

**Comment by doombeaker** [comment]
the "re-run every time without cache" problem will be resolved in this PRhttps://github.com/siliconflow/BizyAir/pull/186
