### ISSUE TITLE
[BUG] 本地 ssl 连接错误

### ISSUE THREAD

**Issue by asynchat** [siliconflow/BizyAir#129]
### Describe the Bug

<img width="808" alt="image" src="https://github.com/user-attachments/assets/96c188fc-ea1d-4a54-92d2-0ec738b6d0e6">
KEY是存在的，然后我在所有请求的地方加了 `context = ssl._create_unverified_context()`，不使用SSL才能正常工作。

### Steps to Reproduce

ComfyUI 启动时，

### Environment

- **OS:** MAC
- **Browser:** Edge

**Comment by doombeaker** [comment]
你好，目前中国以外的部分网络访问 bizyair，可能会因为接入节点的检查而失败。
如果你不在海外，那可能是因为开启了网络代理导致的，可以尝试关闭网络代理后再尝试。

我们正在调整接入节点的检查，减少这类网络失败，谢谢。
