### ISSUE TITLE
[BUG] BizyAir 的节点模型model无法点开

### ISSUE THREAD

**Issue by lfglfg11** [siliconflow/BizyAir#130]
如图点击model
![image](https://github.com/user-attachments/assets/c9c33c3d-cf06-4845-9d74-42ca97b17573)
页面出现提示缺少依赖：You may be missing dependencies at the moment. For details, please refer to the ComfyUI logs.
![image](https://github.com/user-attachments/assets/dd3c6f30-ac9f-47a6-8930-00311df7da5e)
后台并无报错信息，依赖也重装过还是没用
![image](https://github.com/user-attachments/assets/803ae28e-a6f8-4cc0-baf9-149a16ef4113)
浏览器F12报错如下：
![image](https://github.com/user-attachments/assets/6d55ef5d-2330-409f-9357-8e847e811438)

**Comment by terliu** [comment]
你需要安装那个阿里云的服务包

**Comment by lfglfg11** [comment]
> 你需要安装那个阿里云的服务包

能否细说一下具体是哪个包？看不懂

**Comment by DUELISTFEI** [comment]
> > 你需要安装那个阿里云的服务包
> 
> 能否细说一下具体是哪个包？看不懂

python -m pip install aliyun-python-sdk-core -i https://pypi.tuna.tsinghua.edu.cn/simple

**Comment by mrcao2012** [comment]
1、在文件资源管理器中进入D:\ComfyUI_windows_portable\python_embeded目录，就是python目录
2、在上面地址框中输入CMD，进入CMD模式，执行如下命令
3、python -m pip install aliyun-python-sdk-core-v3==2.13.10 -i https://pypi.tuna.tsinghua.edu.cn/simple
我这样安装成功了，如上不成功
