### ISSUE TITLE
[FEATURE REQUEST] lora size wish

### ISSUE THREAD

**Issue by jasoncow007** [siliconflow/BizyAir#136]
lora size restrict less than 100mb is a little bit strict，，，，200mb is  a reasonable choice

**Comment by doombeaker** [comment]
the upload size limit is not set by BizyAir, it is set by comfyui, however, you can set it to a bigger size, please refer to https://bizyair.siliconflow.cn/model-host/introduce.html#comfyui

**Comment by jasoncow007** [comment]
> the upload size limit is not set by BizyAir, it is set by comfyui, however, you can set it to a bigger size, please refer to https://bizyair.siliconflow.cn/model-host/introduce.html#comfyui

ok, 600mb lora uploaded, but cannot work with flux, vram got boomed
Unexpected error accessing result["data"]["payload"]. Result: {'status': 'error', 'message': {'exception_message': 'CUDA out of memory. Tried to allocate 216.00 MiB. GPU '}, 'data': {'error': '0'}}
