### ISSUE TITLE
导入失败

### ISSUE THREAD

**Issue by liuningning123** [siliconflow/BizyAir#142]
Display name '☁️BizyAir SetUnionControlNetType' might differ from the native display name.
Display name '☁️BizyAir IPAdapterModelLoader' might differ from the native display name.
Display name '☁️BizyAir IPAdapterAdvanced' might differ from the native display name.
Display name '☁️BizyAir IPAdapterStyleComposition' might differ from the native display name.
Display name '☁️BizyAir UltimateSDUpscale' might differ from the native display name.
Display name '☁️BizyAir MinusZoneChatGLM3TextEncode' might differ from the native display name.

0.4 seconds (IMPORT FAILED): D:\ComfyUI-aki-v1.4\custom_nodes\BizyAir

一直导入失败

**Comment by doombeaker** [comment]
https://github.com/siliconflow/BizyAir/pull/143

谢谢反馈，这个问题应该已经被这个pr修复了，可以更新BizyAir试试。
