### ISSUE TITLE
[FEATURE REQUEST] Is it possible to add more model options for BizyAirSiliconCloudLLMAPI nodes, qwen2.5-7b vs. 72b

### ISSUE THREAD

**Issue by VAVAVAAA** [siliconflow/BizyAir#147]
![image](https://github.com/user-attachments/assets/e2ab942f-7554-4207-b87f-70cf2bd15829)

**Comment by doombeaker** [comment]
of course, it will be updated soon

**Comment by doombeaker** [comment]
It will be resolved in https://github.com/siliconflow/BizyAir/pull/135

**Comment by doombeaker** [comment]
https://github.com/siliconflow/BizyAir/pull/135 has been merged, all the LLM models of SiliconCloud can be used in BizyAir

![image](https://github.com/user-attachments/assets/23be0e38-9a37-4c03-8012-c61bdf7920e1)
