### ISSUE TITLE
Hopefully the API will be saved to a local directory

### ISSUE THREAD

**Issue by yiwangsimple** [siliconflow/BizyAir#16]
Can you add a config.json file to save this api, big guy. It's too hard to refill the API every time I refresh the workflow.

**Comment by doombeaker** [comment]
Hello, actually the API key is stored in the local cookies. Once set, it does not need to be entered repeatedly.

In fact, as long as the prompt box that reminds you to enter the API key does not pop up, it means that the cookies have not expired and all the nodes can be used directly.

**Comment by yiwangsimple** [comment]
Refresh your browser and the expiration date will pop up!

**Comment by doombeaker** [comment]
> Refresh your browser and the expiration date will pop up!

Unless you actively clear the cache and cookies, simply refreshing the page will not clear the cookies (API key). 

It's possible that when you restart ComfyUI, you might change the port number, which makes the browser consider it a new site, and thus it cannot find the key. 

In any case, please let me know if you have any issues
