### ISSUE TITLE
[FEATURE REQUEST] Support New Alpha two Version

### ISSUE THREAD

**Issue by zyc6581750** [siliconflow/BizyAir#161]
https://huggingface.co/spaces/fancyfeast/joy-caption-alpha-two

The new version adds many options

**Comment by DanielYuan1993** [comment]
+1

**Comment by doombeaker** [comment]
sure, we will support it

**Comment by doombeaker** [comment]
joy caption 2 and joycaption1 are both supported in bizyair now
