### ISSUE TITLE
[BUG] ComfyUI can't start 

### ISSUE THREAD

**Issue by 6sixteen** [siliconflow/BizyAir#171]
### Describe the Bug

WebSocket connection to 'ws://127.0.0.1:8188/bizyair/modelhost/ws?clientId=2dbb5929fd0c4421a9046dc2e6e67d06' failed: 

### Steps to Reproduce

Please provide the workflow or steps to reproduce the bug.

### Environment

- **OS:** [e.g.,  Windows 10 ]
- **Browser:** [e.g., chrome ]

### Additional Context

ComfyUI can't start.
F12  WebSocket connection to 'ws://127.0.0.1:8188/bizyair/modelhost/ws?clientId=2dbb5929fd0c4421a9046dc2e6e67d06' failed:

**Comment by doombeaker** [comment]
Based on the information provided, I am unable to reproduce this issue. Please update to the latest version of BizyAir and restart your system to attempt a resolution.
