### ISSUE TITLE
[FEATURE REQUEST]flix use lora will cause 1024*1024 limit，plz set it as 1536 like before

### ISSUE THREAD

**Issue by jasoncow007** [siliconflow/BizyAir#178]
### ComfyUI Node Repository
flux use lora has no limit like this, until pulid for flux comes up,,,

**Comment by doombeaker** [comment]
it is not a limit caused by pulid. We will lift this restriction to 1536*1536 after the public beta of BizyAir ends.

by the way, the 1024*1024 limit in fact has been lift to 1280*1280
