### ISSUE TITLE
[BUG] sd3.5 cannot work with ksampler advanced?

### ISSUE THREAD

**Issue by jasoncow007** [siliconflow/BizyAir#182]
### Describe the Bug

error as bellow when using ksampler advanced to step sampling for sd3.5

RuntimeError: Unexpected error accessing result["data"]["payload"]. Result: {'type': 'error', 'message': 'Error processing task 1b03adf7-6271-4210-aa52-31540e327702: Exceeded limit for instance KSamplerAdvanced count <= 0.', 'details': 'Traceback (most recent call last):\n  File "/workspace/comfybridge/comfybridge/bizyair/schedulers.py", line 287, in process_request\n    result = await self._execute_task(\n  File "/workspace/comfybridge/comfybridge/bizyair/schedulers.py", line 331, in _execute_task\n    return await loop.run_in_executor(self.pool, executor.execute)\n  File "/opt/conda/lib/python3.10/concurrent/futures/thread.py", line 58, in run\n    result = self.fn(*self.args, **self.kwargs)\n  File "/workspace/comfybridge/comfybridge/bizyair/schedulers.py", line 80, in execute\n    return self.execute_func(*self.args, **self.kwargs)\n  File "/workspace/comfybridge/comfybridge/plugins/comfy_pipeline/utils/cuda_memory_utils.py", line 22, in wrapper\n    result = func(*args, **kwargs)\n  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context\n    return func(*args, **kwargs)\n  File "/workspace/comfybridge/comfybridge/plugins/comfy_pipeline/server.py", line 101, in run\n    user_params: ServerFormat = convert_to_server_format(\n  File "/workspace/comfybridge/comfybridge/plugins/comfy_pipeline/transpiler/transpiler.py", line 80, in convert_to_server_format\n    prompt, node_id_registry = allocator.generate_workflow_with_allocated_ids(\n  File "/workspace/comfybridge/comfybridge/plugins/comfy_pipeline/transpiler/node_id_allocator.py", line 108, in generate_workflow_with_allocated_ids\n    raise RuntimeError(\nRuntimeError: Exceeded limit for instance KSamplerAdvanced count <= 0\n', 'extra_info': None, 'data_status': 'COMPLETED', 'start_time': 1729830144.9027796, 'end_time': 1729830144.9329367, 'task_id': '1b03adf7-6271-4210-aa52-31540e327702', 'upload_to_s3': None}

**Comment by doombeaker** [comment]
It has been resolved, please update your BizyAir and try it again
