### ISSUE TITLE
You can upload the loras and use it by you own, please refer to https://siliconflow.github.io/BizyAir/model-host/introduce.html to get details.

### ISSUE THREAD

**Issue by syl1130** [siliconflow/BizyAir#188]
You can upload the loras and use it by you own, please refer to https://siliconflow.github.io/BizyAir/model-host/introduce.html to get details.

flux controlnet will be supported in a few weeks, you can upload your own controlnet and use it by BizyAir then.

RF Inversion is not on the to do list so far.

Thank you for your advice!

_Originally posted by @doombeaker in https://github.com/siliconflow/BizyAir/issues/184#issuecomment-2437592158_

![image](https://github.com/user-attachments/assets/8ecd5c4e-3cd0-481f-91e4-0f257b60fff7)

What is the reason for this error?

**Comment by doombeaker** [comment]
the requirements.txt not installed successfully ( oss2 package is not installed successfully on your device).

please see the terminal output for more details

**Comment by syl1130** [comment]
> requirements.txt 未成功安装（ oss2 包未在您的设备上成功安装）。
> 
> 请查看终端输出以了解更多详细信息

C:\Users\SYL\Desktop\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[92m[BizyAir][0m Try to install depency oss2
Collecting oss2
  Using cached oss2-2.19.1.tar.gz (298 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: requests!=2.9.0 in c:\users\syl\desktop\comfyui_windows_portable\python_embeded\lib\site-packages (from oss2) (2.32.3)
Collecting crcmod>=1.7 (from oss2)
  Using cached crcmod-1.7-py3-none-any.whl
Collecting pycryptodome>=3.4.7 (from oss2)
  Using cached pycryptodome-3.21.0-cp36-abi3-win_amd64.whl.metadata (3.4 kB)
Collecting aliyun-python-sdk-kms>=2.4.1 (from oss2)
  Using cached aliyun_python_sdk_kms-2.16.5-py2.py3-none-any.whl.metadata (1.5 kB)
Collecting aliyun-python-sdk-core>=2.13.12 (from oss2)
  Using cached aliyun-python-sdk-core-2.16.0.tar.gz (449 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\SYL\AppData\Local\Temp\pip-install-qhv4_377\aliyun-python-sdk-core_0b7b520976e14b55ba6769053b081db3\setup.py", line 41, in <module>
          VERSION = __import__(PACKAGE).__version__
                    ^^^^^^^^^^^^^^^^^^^
      ModuleNotFoundError: No module named 'aliyunsdkcore'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
[91m[BizyAir][0m Failed to install oss2: Command '['C:\\Users\\SYL\\Desktop\\ComfyUI_windows_portable\\python_embeded\\python.exe', '-m', 'pip', 'install', 'oss2']' returned non-zero exit status 1.
[92m[BizyAir][0m Try to install depency crcmod
Collecting crcmod
  Using cached crcmod-1.7-py3-none-any.whl
Installing collected packages: crcmod
Successfully installed crcmod-1.7
[92m[BizyAir][0m Try to install depency aiofiles
Collecting aiofiles
  Using cached aiofiles-24.1.0-py3-none-any.whl.metadata (10 kB)
Using cached aiofiles-24.1.0-py3-none-any.whl (15 kB)
Installing collected packages: aiofiles
Successfully installed aiofiles-24.1.0

Prestartup times for custom nodes:
   8.9 seconds: C:\Users\SYL\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\BizyAir

Traceback (most recent call last):
  File "C:\Users\SYL\Desktop\ComfyUI_windows_portable\ComfyUI\main.py", line 90, in <module>
    import execution
  File "C:\Users\SYL\Desktop\ComfyUI_windows_portable\ComfyUI\execution.py", line 13, in <module>
    import nodes
  File "C:\Users\SYL\Desktop\ComfyUI_windows_portable\ComfyUI\nodes.py", line 21, in <module>
    import comfy.diffusers_load
  File "C:\Users\SYL\Desktop\ComfyUI_windows_portable\ComfyUI\comfy\diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "C:\Users\SYL\Desktop\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 5, in <module>
    from comfy import model_management
  File "C:\Users\SYL\Desktop\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 143, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
                                  ^^^^^^^^^^^^^^^^^^
  File "C:\Users\SYL\Desktop\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 112, in get_torch_device
    return torch.device(torch.cuda.current_device())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SYL\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\cuda\__init__.py", line 878, in current_device
    _lazy_init()
  File "C:\Users\SYL\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\cuda\__init__.py", line 305, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

C:\Users\SYL\Desktop\ComfyUI_windows_portable>pause
请按任意键继续. . .

**Comment by syl1130** [comment]
@doombeaker  您好，以上是详细信息，我没有代码能力，使用了四种方法安装都是显示以上信息，上传模型使用不了，感谢您百忙之中技术支持
