### ISSUE TITLE
May I ask if it is only possible to generate two at a time, when the Vince map

### ISSUE THREAD

**Issue by yiwangsimple** [siliconflow/BizyAir#20]
Error occurred when executing BizyAirKolorsTextEncode:

number of prompts must be less than 2, but got 3 and 1, reduce the '|' symbol

File "/Users/weiwei/ComfyUI/execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/Users/weiwei/ComfyUI/execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/Users/weiwei/ComfyUI/execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/Users/weiwei/ComfyUI/custom_nodes/BizyAir/kolors.py", line 46, in encode
assert (

**Comment by doombeaker** [comment]
Yes, currently the limit for prompts number is 2, and the limit for generating images per prompt is also 2.
This restriction is in place to allow more people to share BizyAir's computational resources.

Could generating 2 images at a time and running the workflow multiple times solve your issue?

**Comment by yiwangsimple** [comment]
You can change the max batch to 1 and the cue sequence to 4, which would solve my problem. Mainly, I want to generate character-consistent paintings in conjunction with the storydiffusion plugin!

**Comment by yiwangsimple** [comment]
Of course it doesn't matter how it doesn't fulfill that need, it's appreciated.

**Comment by doombeaker** [comment]
this issue has been solved with https://github.com/siliconflow/BizyAir/pull/22

images can be generated as long as num_per_prompt*prompt_nums <=4

please upgrade the BizyAir nodes and enjoy it.
