### ISSUE TITLE
请添加segment-anything2-medical-evaluation这个抠图功能更好的插件——https://github.com/mazurowski-lab/segment-anything2-medical-evaluation.git

### ISSUE THREAD

**Issue by zhuzhuxia2024** [siliconflow/BizyAir#203]
### ComfyUI Node Repository

Please provide the repository URL of the ComfyUI node you are referring to:

- Repository URL: [e.g., https://github.com/user/repo]

### Node Description and Use Case

Describe the purpose of the node and the scenarios in which it is used:

- Node Description: [e.g., This node is used for generating high-quality images from textual descriptions.]
- Use Case: [e.g., Ideal for graphic designers looking to quickly prototype designs using text inputs.]

### Workflow Details (optional)

Please provide details about the workflow, including links, screenshots, or JSON files:

- Workflow Link: [e.g., https://example.com/workflow]
- Screenshots: [If applicable, please attach screenshots here.]
- JSON File: [If applicable, please attach the JSON file or provide a link to it.]

### Additional Context (optional)

Add any other context or information about the feature request here.

**Comment by zhuzhuxia2024** [comment]
https://github.com/mazurowski-lab/segment-anything2-medical-evaluation.git这是插件网址

**Comment by doombeaker** [comment]
segment anything 2 的优势，更体现在视频抠图上。我们在未来支持视频节点后，再做相关的工作。
