### ISSUE TITLE
[FEATURE REQUEST] 希望添加 细节增强 节点功能 ComfyUI-Detail-Daemon for BizyAir

### ISSUE THREAD

**Issue by syl1130** [siliconflow/BizyAir#204]
### ComfyUI Node Repository

- Repository URL: https://github.com/Jonseed/ComfyUI-Detail-Daemon

### Node Description and Use Case

Describe the purpose of the node and the scenarios in which it is used:

to adjust sigmas that generally enhance details, and possibly remove unwanted bokeh or background blurring, particularly with Flux models (but also works with SDXL, SD1.5, and likely other models). If the values are taken too far it results in an oversharpened and/or HDR effect.

### Workflow Details (optional)

- Workflow Link: https://github.com/Jonseed/ComfyUI-Detail-Daemon#example-and-testing-workflows

### Additional Context (optional)

![image](https://github.com/user-attachments/assets/da59c9a7-5ecc-4992-a76c-eac20829eaf1)

**Comment by doombeaker** [comment]
https://github.com/siliconflow/BizyAir/pull/271

it has been supported in the PR above.
