### ISSUE TITLE
[BUG] You may be missing dependencies at the moment. For details, please refer to the ComfyUI logs.

### ISSUE THREAD

**Issue by balumiisa** [siliconflow/BizyAir#217]
![20241113130956802](https://github.com/user-attachments/assets/4eabbed6-8dcc-4412-8db3-9aa00a9dbe09)
![20241113131923884](https://github.com/user-attachments/assets/516fe57f-cf2d-42c5-853e-f28b72e8f1dc)
It installs normally and fills in the API key, but it always prompts these errors and can't upload the model. What can I do to solve this problem?

**Comment by doombeaker** [comment]
please try:
1. update your BizyAir
2. close your http prxoy if you use it
3. restart the ComfyUI
