### ISSUE TITLE
[BUG] FLUX放大模型跑不通

### ISSUE THREAD

**Issue by guyuehu2304** [siliconflow/BizyAir#225]
![放大](https://github.com/user-attachments/assets/9d009863-480f-4c42-b2e8-c1f7099bca65)
![放大](https://github.com/user-attachments/assets/ed87c9bb-4512-46b6-92de-c3c77d0c1014)

**Comment by guyuehu2304** [comment]
![Uploading 6cf1fc3318d86999a446dfcba0b7760.png…]()

**Comment by doombeaker** [comment]
可以先用这个：

[放大cnflux.json](https://github.com/user-attachments/files/17797962/cnflux.json)
