### ISSUE TITLE
可以连接 非BizyAir节点 吗

### ISSUE THREAD

**Issue by lazyracket** [siliconflow/BizyAir#232]
好像`BizyAir节点`仅能连接`BizyAir节点`

**想实现与本地其他节点混合使用，是否有这方面的技巧或指南**

> `文字`和`图像`这类信息，好像可以和`非BizyAir节点`进行传递

**Comment by doombeaker** [comment]
暂时只有 latent, image, text可以连接。
模型不能连接本地节点
