### ISSUE TITLE
[BUG]apply redux advanced issue

### ISSUE THREAD

**Issue by jasoncow007** [siliconflow/BizyAir#259]
Unexpected error accessing result["data"]["payload"]. Result: {'type': 'error', 'message': "Error processing task 574577a5-09a9-4feb-a23b-69dbac0b3f51: 'ReduxAdvanced'.", 'details': 'Traceback (most recent call last):\n File "/workspace/comfybridge/comfybridge/bizyair/schedulers.py", line 287, in process_request\n task.start_time = time.time()\n File "/workspace/comfybridge/comfybridge/bizyair/schedulers.py", line 341, in _execute_task\n authorization=authorization,\n File "/opt/conda/lib/python3.10/concurrent/futures/thread.py", line 58, in run\n result = self.fn(*self.args, **self.kwargs)\n File "/workspace/comfybridge/comfybridge/bizyair/schedulers.py", line 80, in execute\n return self.execute_func(*self.args, **self.kwargs)\n File "/workspace/comfybridge/comfybridge/plugins/comfy_pipeline/utils/cuda_memory_utils.py", line 37, in wrapper\n result = func(*args, **kwargs)\n File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context\n return func(*args, **kwargs)\n File "/workspace/comfybridge/comfybridge/plugins/comfy_pipeline/server.py", line 125, in run\n user_params: ServerFormat = convert_to_server_format(\n File "/workspace/comfybridge/comfybridge/plugins/comfy_pipeline/transpiler/transpiler.py", line 68, in convert_to_server_format\n comfy_graph = ComfyGraph.from_data(workflow, verbose=verbose)\n File "/workspace/comfybridge/comfybridge/plugins/comfy_pipeline/transpiler/comfy_objects.py", line 346, in from_data\n return cls(prompt=prompt, verbose=verbose, max_node_id=max_node_id)\n File "<string>", line 7, in __init__\n File "/workspace/comfybridge/comfybridge/plugins/comfy_pipeline/transpiler/comfy_objects.py", line 314, in __post_init__\n prompt_pre_run(self.prompt)\n File "/workspace/comfybridge/comfybridge/plugins/comfy_pipeline/transpiler/comfy_objects.py", line 44, in prompt_pre_run\n class_def = nodes.NODE_CLASS_MAPPINGS[class_type]\nKeyError: \'ReduxAdvanced\'\n', 'extra_info': None, 'data_status': 'COMPLETED', 'start_time': 1733363549.7651627, 'end_time': 1733363550.0388393, 'task_id': '574577a5-09a9-4feb-a23b-69dbac0b3f51', 'upload_to_s3': None}

**Comment by doombeaker** [comment]
请按照模板，提供环境、工作流、报错信息（已经有了）等内容
