### ISSUE TITLE
[BUG] 浮动条上的菜单都没了

### ISSUE THREAD

**Issue by AdamShuo** [siliconflow/BizyAir#264]
### Describe the Bug

更新以后Bizyair浮动条上的菜单全都没了！
如下图：
![image](https://github.com/user-attachments/assets/567aee4f-ba74-4ef3-9979-ddea5952e8e9)

### Steps to Reproduce

Please provide the workflow or steps to reproduce the bug.

### Environment

- **OS:** [e.g., Linux Ubuntu 12.04, Windows 10]
- **Browser:** [e.g., chrome, safari]

**Comment by Of-qinhai** [comment]
方便提供一下comfyui 版本吗？

**Comment by huameiwei-vc** [comment]
我也是这样的，就是最新版的 comfyui，刚安装的。

**Comment by huameiwei-vc** [comment]
Display name '☁️BizyAir SetUnionControlNetType' might differ from the native display name.
Display name '☁️BizyAir ControlNetInpaintingAliMamaApply' might differ from the native display name.
Display name '☁️BizyAir DisableNoise' might differ from the native display name.
Display name '☁️BizyAir FlipSigmas' might differ from the native display name.
Display name '☁️BizyAir CFGGuider' might differ from the native display name.
Display name '☁️BizyAir CLIPTextEncodeFlux' might differ from the native display name.
Display name '☁️BizyAir FluxGuidance' might differ from the native display name.
Display name '☁️BizyAir InstructPixToPixConditioning' might differ from the native display name.
Display name '☁️BizyAir ModelSamplingSD3' might differ from the native display name.
Display name '☁️BizyAir ModelSamplingFlux' might differ from the native display name.
Display name '☁️BizyAir TripleCLIPLoader' might differ from the native display name.
Display name '☁️BizyAir UltimateSDUpscale' might differ from the native display name.
Display name '☁️BizyAir MinusZoneChatGLM3TextEncode' might differ from the native display name.
Display name '☁️BizyAir LoraLoader_Legacy' might differ from the native display name.
Display name '☁️BizyAir ControlNetLoader_Legacy' might differ from the native display name.
Display name '☁️BizyAir SamplerCustomAdvanced' might differ from the native display name.
Display name '☁️BizyAir BasicGuider' might differ from the native display name.
Display name '☁️BizyAir BasicScheduler' might differ from the native display name.
Display name '☁️BizyAir DualCLIPLoader' might differ from the native display name.
Display name '☁️BizyAir KSamplerSelect' might differ from the native display name.
Display name '☁️BizyAir RandomNoise' might differ from the native display name.
Display name '☁️BizyAir InpaintModelConditioning' might differ from the native display name.
Display name '☁️BizyAir InpaintModelConditioning_v2' might differ from the native display name.
Display name '☁️BizyAir ConditioningZeroOut' might differ from the native display name.
Display name '☁️BizyAir ConditioningSetTimestepRange' might differ from the native display name.

**Comment by AdamShuo** [comment]
> 方便提供一下comfyui 版本吗？

0.3.7

**Comment by Of-qinhai** [comment]
刚下载的最新版，没复现上面的问题，是装了其它的插件冲突了吗？

https://github.com/user-attachments/assets/4ac3c61b-d52e-4535-9568-2950fa7a06b2

**Comment by AdamShuo** [comment]
> > > 方便提供一下comfyui 版本吗？
> > 
> > 
> > 0.3.7
> 
> 拉取最新版的BizyAir ,master 分支，重试一下

云端还是一样，估计是和什么插件冲突了，我另一个本地的就没事，我排查一下

**Comment by AdamShuo** [comment]
> > > > 方便提供一下comfyui 版本吗？
> > > 
> > > 
> > > 0.3.7
> > 
> > 
> > 拉取最新版的BizyAir ,master 分支，重试一下
> 
> 云端还是一样，估计是和什么插件冲突了，我另一个本地的就没事，我排查一下

彻底删掉重装就好了

**Comment by huameiwei-vc** [comment]
还是不行，更新 comfyui，重装都不好使。。。我也是云端。

**Comment by Of-qinhai** [comment]
> 还是不行，更新 comfyui，重装都不好使。。。我也是云端。

除了Bizyair还安装了别的插件吗？

**Comment by doombeaker** [comment]
这个问题安装最新的 BizyAir 可以解决。不过要注意，如果使用的是 ComfyUI Manager 一类的管理工具，有可能 ComfyUI Manager 没有收录最新的 BizyAir。
比较保险的方式，是删除 `custom_nodes/BizyAir` 目录，然后在本仓库下载 zip 包，解压到 `custom_nodes` 下。

**Comment by doombeaker** [comment]
如果你使用的是一些云服务器遇到了这个问题，很可能是插件及 ComfyUI 本体不兼容的问题。

有用户尝试把 ComfyUI 版本退回到 0.2.4 就可以用了。

![image](https://github.com/user-attachments/assets/83163b74-620e-46dc-bbe9-6e51867def97)

**Comment by AdamShuo** [comment]
现在ComfyUI都0.3.7了，回退到0.2.4好多功能不能用，还不如回退BizyAir版本，我之前从gitclone.com克隆的可以用，用下来才发现是很旧版本的BizyAir。我再试试删掉从原始地址克隆。

**Comment by AdamShuo** [comment]
> 现在ComfyUI都0.3.7了，回退到0.2.4好多功能不能用，还不如回退BizyAir版本，我之前从gitclone.com克隆的可以用，用下来才发现是很旧版本的BizyAir。我再试试删掉从原始地址克隆。

刚试了一下，安装了最新版的还是不行，暂时从其他实例加载工作流再拷过去，在其他实例操作上传管理模型吧

**Comment by tangzi** [comment]
![image](https://github.com/user-attachments/assets/955fd563-b388-427c-a597-63e6a9e57189)
找原因了，comfyui默认都是本地部署，走的是http的请求，在云服务部署往往都是https，bizyair插件bizyair_frontend.js代码中的141行，ws://不能有http请求，暂时把141里的ws改成wss，就可以正常使用了，希望插件作者后边能做兼容性修改

**Comment by AdamShuo** [comment]
> > > 现在ComfyUI都0.3.7了，回退到0.2.4好多功能不能用，还不如回退BizyAir版本，我之前从gitclone.com克隆的可以用，用下来才发现是很旧版本的BizyAir。我再试试删掉从原始地址克隆。
> > 
> > 
> > 刚试了一下，安装了最新版的还是不行，暂时从其他实例加载工作流再拷过去，在其他实例操作上传管理模型吧
> 
> 你是不是用的云环境跑的 ComfyUI，有其它的用户反馈类似的问题，是云环境（不是本地的 ComfyUI）

对，云环境，就是最新一版BizyAir出现的这个问题。

**Comment by doombeaker** [comment]
这个问题已经由 https://github.com/siliconflow/BizyAir/pull/269 修复。

有类似问题的同学，拉取最新的 BizyAir 就可以解决问题啦。
