### ISSUE TITLE
[BUG] how to publish a model, tried several versions, and path too

### ISSUE THREAD

**Issue by jasoncow007** [siliconflow/BizyAir#267]
![image](https://github.com/user-attachments/assets/78165fd3-26fb-43e8-9e8f-50f424f50733)

**Comment by doombeaker** [comment]
![image](https://github.com/user-attachments/assets/d717b06b-7146-40b5-836d-fff115aab2d4)

**Comment by jasoncow007** [comment]
already uploaded file, the error message is about the path
