### ISSUE TITLE
Controlnet Union 工作流无法使用了[BUG] 

### ISSUE THREAD

**Issue by AdamShuo** [siliconflow/BizyAir#273]
### Describe the Bug

Dec 11 18:51:13 xb2-4011 bash[23767]: !!! Exception during processing !!! HTTPSConnectionPool(host='bizyair-api.siliconflow.cn', port=443): Max retries exceeded with url: /x/v1/supernode/diffusers-v1-stablediffusionxlcontrolnetunionpipeline (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')))
Dec 11 18:51:13 xb2-4011 bash[23767]: urllib3.exceptions.SSLError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)
Dec 11 18:51:13 xb2-4011 bash[23767]: The above exception was the direct cause of the following exception:
Dec 11 18:51:13 xb2-4011 bash[23767]: Traceback (most recent call last):
Dec 11 18:51:13 xb2-4011 bash[23767]:   File "/root/miniconda3/lib/python3.11/site-packages/requests/adapters.py", line 667, in send
Dec 11 18:51:13 xb2-4011 bash[23767]:     resp = conn.urlopen(
Dec 11 18:51:13 xb2-4011 bash[23767]:            ^^^^^^^^^^^^^
Dec 11 18:51:13 xb2-4011 bash[23767]:   File "/root/miniconda3/lib/python3.11/site-packages/urllib3/connectionpool.py", line 843, in urlopen
Dec 11 18:51:13 xb2-4011 bash[23767]:     retries = retries.increment(
Dec 11 18:51:13 xb2-4011 bash[23767]:               ^^^^^^^^^^^^^^^^^^
Dec 11 18:51:13 xb2-4011 bash[23767]:   File "/root/miniconda3/lib/python3.11/site-packages/urllib3/util/retry.py", line 519, in increment
Dec 11 18:51:13 xb2-4011 bash[23767]:     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
Dec 11 18:51:13 xb2-4011 bash[23767]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 11 18:51:13 xb2-4011 bash[23767]: urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='bizyair-api.siliconflow.cn', port=443): Max retries exceeded with url: /x/v1/supernode/diffusers-v1-stablediffusionxlcontrolnetunionpipeline (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')))
Dec 11 18:51:13 xb2-4011 bash[23767]: During handling of the above exception, another exception occurred:
Dec 11 18:51:13 xb2-4011 bash[23767]: Traceback (most recent call last):
Dec 11 18:51:13 xb2-4011 bash[23767]:   File "/root/ComfyUI/execution.py", line 323, in execute
Dec 11 18:51:13 xb2-4011 bash[23767]:     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
Dec 11 18:51:13 xb2-4011 bash[23767]:                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 11 18:51:13 xb2-4011 bash[23767]:   File "/root/ComfyUI/execution.py", line 198, in get_output_data
Dec 11 18:51:13 xb2-4011 bash[23767]:     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
Dec 11 18:51:13 xb2-4011 bash[23767]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 11 18:51:13 xb2-4011 bash[23767]:   File "/root/ComfyUI/execution.py", line 169, in _map_node_over_list
Dec 11 18:51:13 xb2-4011 bash[23767]:     process_inputs(input_dict, i)
Dec 11 18:51:13 xb2-4011 bash[23767]:   File "/root/ComfyUI/execution.py", line 158, in process_inputs
Dec 11 18:51:13 xb2-4011 bash[23767]:     results.append(getattr(obj, func)(**inputs))
Dec 11 18:51:13 xb2-4011 bash[23767]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 11 18:51:13 xb2-4011 bash[23767]:   File "/root/ComfyUI/custom_nodes/BizyAir/nodes_controlnet_union_sdxl.py", line 144, in process
Dec 11 18:51:13 xb2-4011 bash[23767]:     response = requests.post(
Dec 11 18:51:13 xb2-4011 bash[23767]:                ^^^^^^^^^^^^^^
Dec 11 18:51:13 xb2-4011 bash[23767]:   File "/root/miniconda3/lib/python3.11/site-packages/requests/api.py", line 115, in post
Dec 11 18:51:13 xb2-4011 bash[23767]:     return request("post", url, data=data, json=json, **kwargs)
Dec 11 18:51:13 xb2-4011 bash[23767]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 11 18:51:13 xb2-4011 bash[23767]:   File "/root/miniconda3/lib/python3.11/site-packages/requests/api.py", line 59, in request
Dec 11 18:51:13 xb2-4011 bash[23767]:     return session.request(method=method, url=url, **kwargs)
Dec 11 18:51:13 xb2-4011 bash[23767]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 11 18:51:13 xb2-4011 bash[23767]:   File "/root/miniconda3/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
Dec 11 18:51:13 xb2-4011 bash[23767]:     resp = self.send(prep, **send_kwargs)
Dec 11 18:51:13 xb2-4011 bash[23767]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 11 18:51:13 xb2-4011 bash[23767]:   File "/root/miniconda3/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
Dec 11 18:51:13 xb2-4011 bash[23767]:     r = adapter.send(request, **kwargs)
Dec 11 18:51:13 xb2-4011 bash[23767]:         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 11 18:51:13 xb2-4011 bash[23767]:   File "/root/miniconda3/lib/python3.11/site-packages/requests/adapters.py", line 698, in send
Dec 11 18:51:13 xb2-4011 bash[23767]:     raise SSLError(e, request=request)
Dec 11 18:51:13 xb2-4011 bash[23767]: requests.exceptions.SSLError: HTTPSConnectionPool(host='bizyair-api.siliconflow.cn', port=443): Max retries exceeded with url: /x/v1/supernode/diffusers-v1-stablediffusionxlcontrolnetunionpipeline (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')))
Dec 11 18:51:13 xb2-4011 bash[23767]: Prompt executed in 15.05 seconds
Dec 11 18:51:53 xb2-4011 bash[23767]: got prompt
Dec 11 18:51:53 xb2-4011 bash[23767]: Utilizing a height of 1024 and width of 1024 for processing.
Dec 11 18:51:58 xb2-4011 bash[23767]: !!! Exception during processing !!! HTTPSConnectionPool(host='bizyair-api.siliconflow.cn', port=443): Max retries exceeded with url: /x/v1/supernode/diffusers-v1-stablediffusionxlcontrolnetunionpipeline (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')))
Dec 11 18:51:58 xb2-4011 bash[23767]: urllib3.exceptions.SSLError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)
Dec 11 18:51:58 xb2-4011 bash[23767]: The above exception was the direct cause of the following exception:
Dec 11 18:51:58 xb2-4011 bash[23767]: Traceback (most recent call last):
Dec 11 18:51:58 xb2-4011 bash[23767]:   File "/root/miniconda3/lib/python3.11/site-packages/requests/adapters.py", line 667, in send
Dec 11 18:51:58 xb2-4011 bash[23767]:     resp = conn.urlopen(
Dec 11 18:51:58 xb2-4011 bash[23767]:            ^^^^^^^^^^^^^
Dec 11 18:51:58 xb2-4011 bash[23767]:   File "/root/miniconda3/lib/python3.11/site-packages/urllib3/connectionpool.py", line 843, in urlopen
Dec 11 18:51:58 xb2-4011 bash[23767]:     retries = retries.increment(
Dec 11 18:51:58 xb2-4011 bash[23767]:               ^^^^^^^^^^^^^^^^^^
Dec 11 18:51:58 xb2-4011 bash[23767]:   File "/root/miniconda3/lib/python3.11/site-packages/urllib3/util/retry.py", line 519, in increment
Dec 11 18:51:58 xb2-4011 bash[23767]:     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
Dec 11 18:51:58 xb2-4011 bash[23767]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 11 18:51:58 xb2-4011 bash[23767]: urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='bizyair-api.siliconflow.cn', port=443): Max retries exceeded with url: /x/v1/supernode/diffusers-v1-stablediffusionxlcontrolnetunionpipeline (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')))
Dec 11 18:51:58 xb2-4011 bash[23767]: During handling of the above exception, another exception occurred:
Dec 11 18:51:58 xb2-4011 bash[23767]: Traceback (most recent call last):
Dec 11 18:51:58 xb2-4011 bash[23767]:   File "/root/ComfyUI/execution.py", line 323, in execute
Dec 11 18:51:58 xb2-4011 bash[23767]:     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
Dec 11 18:51:58 xb2-4011 bash[23767]:                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 11 18:51:58 xb2-4011 bash[23767]:   File "/root/ComfyUI/execution.py", line 198, in get_output_data
Dec 11 18:51:58 xb2-4011 bash[23767]:     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
Dec 11 18:51:58 xb2-4011 bash[23767]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 11 18:51:58 xb2-4011 bash[23767]:   File "/root/ComfyUI/execution.py", line 169, in _map_node_over_list
Dec 11 18:51:58 xb2-4011 bash[23767]:     process_inputs(input_dict, i)
Dec 11 18:51:58 xb2-4011 bash[23767]:   File "/root/ComfyUI/execution.py", line 158, in process_inputs
Dec 11 18:51:58 xb2-4011 bash[23767]:     results.append(getattr(obj, func)(**inputs))
Dec 11 18:51:58 xb2-4011 bash[23767]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 11 18:51:58 xb2-4011 bash[23767]:   File "/root/ComfyUI/custom_nodes/BizyAir/nodes_controlnet_union_sdxl.py", line 144, in process
Dec 11 18:51:58 xb2-4011 bash[23767]:     response = requests.post(
Dec 11 18:51:58 xb2-4011 bash[23767]:                ^^^^^^^^^^^^^^
Dec 11 18:51:58 xb2-4011 bash[23767]:   File "/root/miniconda3/lib/python3.11/site-packages/requests/api.py", line 115, in post
Dec 11 18:51:58 xb2-4011 bash[23767]:     return request("post", url, data=data, json=json, **kwargs)
Dec 11 18:51:58 xb2-4011 bash[23767]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 11 18:51:58 xb2-4011 bash[23767]:   File "/root/miniconda3/lib/python3.11/site-packages/requests/api.py", line 59, in request
Dec 11 18:51:58 xb2-4011 bash[23767]:     return session.request(method=method, url=url, **kwargs)
Dec 11 18:51:58 xb2-4011 bash[23767]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 11 18:51:58 xb2-4011 bash[23767]:   File "/root/miniconda3/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
Dec 11 18:51:58 xb2-4011 bash[23767]:     resp = self.send(prep, **send_kwargs)
Dec 11 18:51:58 xb2-4011 bash[23767]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 11 18:51:58 xb2-4011 bash[23767]:   File "/root/miniconda3/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
Dec 11 18:51:58 xb2-4011 bash[23767]:     r = adapter.send(request, **kwargs)
Dec 11 18:51:58 xb2-4011 bash[23767]:         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 11 18:51:58 xb2-4011 bash[23767]:   File "/root/miniconda3/lib/python3.11/site-packages/requests/adapters.py", line 698, in send
Dec 11 18:51:58 xb2-4011 bash[23767]:     raise SSLError(e, request=request)
Dec 11 18:51:58 xb2-4011 bash[23767]: requests.exceptions.SSLError: HTTPSConnectionPool(host='bizyair-api.siliconflow.cn', port=443): Max retries exceeded with url: /x/v1/supernode/diffusers-v1-stablediffusionxlcontrolnetunionpipeline (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')))
Dec 11 18:51:58 xb2-4011 bash[23767]: Prompt executed in 5.27 seconds
Dec 11 18:52:12 xb2-4011 bash[23767]: got prompt
Dec 11 18:52:12 xb2-4011 bash[23767]: Utilizing a height of 1024 and width of 1024 for processing.
Dec 11 18:52:17 xb2-4011 bash[23767]: !!! Exception during processing !!! HTTPSConnectionPool(host='bizyair-api.siliconflow.cn', port=443): Max retries exceeded with url: /x/v1/supernode/diffusers-v1-stablediffusionxlcontrolnetunionpipeline (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')))
Dec 11 18:52:17 xb2-4011 bash[23767]: urllib3.exceptions.SSLError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)
Dec 11 18:52:17 xb2-4011 bash[23767]: The above exception was the direct cause of the following exception:
Dec 11 18:52:17 xb2-4011 bash[23767]: Traceback (most recent call last):
Dec 11 18:52:17 xb2-4011 bash[23767]:   File "/root/miniconda3/lib/python3.11/site-packages/requests/adapters.py", line 667, in send
Dec 11 18:52:17 xb2-4011 bash[23767]:     resp = conn.urlopen(
Dec 11 18:52:17 xb2-4011 bash[23767]:            ^^^^^^^^^^^^^
Dec 11 18:52:17 xb2-4011 bash[23767]:   File "/root/miniconda3/lib/python3.11/site-packages/urllib3/connectionpool.py", line 843, in urlopen
Dec 11 18:52:17 xb2-4011 bash[23767]:     retries = retries.increment(
Dec 11 18:52:17 xb2-4011 bash[23767]:               ^^^^^^^^^^^^^^^^^^
Dec 11 18:52:17 xb2-4011 bash[23767]:   File "/root/miniconda3/lib/python3.11/site-packages/urllib3/util/retry.py", line 519, in increment
Dec 11 18:52:17 xb2-4011 bash[23767]:     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
Dec 11 18:52:17 xb2-4011 bash[23767]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 11 18:52:17 xb2-4011 bash[23767]: urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='bizyair-api.siliconflow.cn', port=443): Max retries exceeded with url: /x/v1/supernode/diffusers-v1-stablediffusionxlcontrolnetunionpipeline (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')))
Dec 11 18:52:17 xb2-4011 bash[23767]: During handling of the above exception, another exception occurred:
Dec 11 18:52:17 xb2-4011 bash[23767]: Traceback (most recent call last):
Dec 11 18:52:17 xb2-4011 bash[23767]:   File "/root/ComfyUI/execution.py", line 323, in execute
Dec 11 18:52:17 xb2-4011 bash[23767]:     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
Dec 11 18:52:17 xb2-4011 bash[23767]:                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 11 18:52:17 xb2-4011 bash[23767]:   File "/root/ComfyUI/execution.py", line 198, in get_output_data
Dec 11 18:52:17 xb2-4011 bash[23767]:     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
Dec 11 18:52:17 xb2-4011 bash[23767]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 11 18:52:17 xb2-4011 bash[23767]:   File "/root/ComfyUI/execution.py", line 169, in _map_node_over_list
Dec 11 18:52:17 xb2-4011 bash[23767]:     process_inputs(input_dict, i)
Dec 11 18:52:17 xb2-4011 bash[23767]:   File "/root/ComfyUI/execution.py", line 158, in process_inputs
Dec 11 18:52:17 xb2-4011 bash[23767]:     results.append(getattr(obj, func)(**inputs))
Dec 11 18:52:17 xb2-4011 bash[23767]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 11 18:52:17 xb2-4011 bash[23767]:   File "/root/ComfyUI/custom_nodes/BizyAir/nodes_controlnet_union_sdxl.py", line 144, in process
Dec 11 18:52:17 xb2-4011 bash[23767]:     response = requests.post(
Dec 11 18:52:17 xb2-4011 bash[23767]:                ^^^^^^^^^^^^^^
Dec 11 18:52:17 xb2-4011 bash[23767]:   File "/root/miniconda3/lib/python3.11/site-packages/requests/api.py", line 115, in post
Dec 11 18:52:17 xb2-4011 bash[23767]:     return request("post", url, data=data, json=json, **kwargs)
Dec 11 18:52:17 xb2-4011 bash[23767]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 11 18:52:17 xb2-4011 bash[23767]:   File "/root/miniconda3/lib/python3.11/site-packages/requests/api.py", line 59, in request
Dec 11 18:52:17 xb2-4011 bash[23767]:     return session.request(method=method, url=url, **kwargs)
Dec 11 18:52:17 xb2-4011 bash[23767]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 11 18:52:17 xb2-4011 bash[23767]:   File "/root/miniconda3/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
Dec 11 18:52:17 xb2-4011 bash[23767]:     resp = self.send(prep, **send_kwargs)
Dec 11 18:52:17 xb2-4011 bash[23767]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 11 18:52:17 xb2-4011 bash[23767]:   File "/root/miniconda3/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
Dec 11 18:52:17 xb2-4011 bash[23767]:     r = adapter.send(request, **kwargs)
Dec 11 18:52:17 xb2-4011 bash[23767]:         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 11 18:52:17 xb2-4011 bash[23767]:   File "/root/miniconda3/lib/python3.11/site-packages/requests/adapters.py", line 698, in send
Dec 11 18:52:17 xb2-4011 bash[23767]:     raise SSLError(e, request=request)
Dec 11 18:52:17 xb2-4011 bash[23767]: requests.exceptions.SSLError: HTTPSConnectionPool(host='bizyair-api.siliconflow.cn', port=443): Max retries exceeded with url: /x/v1/supernode/diffusers-v1-stablediffusionxlcontrolnetunionpipeline (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')))

### Steps to Reproduce

Please provide the workflow or steps to reproduce the bug.

### Environment

- **OS:** [e.g., Linux Ubuntu 12.04, Windows 10]
- **Browser:** [e.g., chrome, safari]

**Comment by doombeaker** [comment]
![image](https://github.com/user-attachments/assets/68d36815-4fd2-43ab-93d9-3f4226230008)

你好，未复现出问题。

**Comment by AdamShuo** [comment]
好的，已经更新新版了，但是Controlnet Union又不能用了


[Beta Tester Badge 1][Beta Tester Badge 2][Beta Tester Badge 3]

________________________________
发件人: Yao Chi ***@***.***>
发送时间: 2024年12月11日 11:42
收件人: siliconflow/BizyAir ***@***.***>
抄送: AdamShuo ***@***.***>; Author ***@***.***>
主题: Re: [siliconflow/BizyAir] Controlnet Union 工作流无法使用了[BUG] (Issue #273)


image.png (view on web)<https://github.com/user-attachments/assets/68d36815-4fd2-43ab-93d9-3f4226230008>

你好，未复现出问题。

―
