### ISSUE TITLE
[FEATURE REQUEST] 升级下SAM遮罩提取功能

### ISSUE THREAD

**Issue by tengj** [siliconflow/BizyAir#284]
目前的BizyAir Text Guides SAM效果不是很理想，比本地SAM2差点意思，建议升级一下
下面是我测试的对比结果

<img width="1012" alt="acb667c715868e6ccccb30b2c788562" src="https://github.com/user-attachments/assets/35c6ff17-0e60-4f86-9e27-94e130c2e1a3" />

**Comment by doombeaker** [comment]
done https://github.com/siliconflow/BizyAir/pull/285
