### ISSUE TITLE
[分离sigmas降噪] Support for ComfyUI node in BizyAir

### ISSUE THREAD

**Issue by xiaobao9999** [siliconflow/BizyAir#290]
### ComfyUI Node Repository

<img width="230" alt="876b96cab02de66fc0f1d8dd5b7a745" src="https://github.com/user-attachments/assets/35dbd832-ac53-45b0-9889-442a98c31eb5" />

Please provide the repository URL of the ComfyUI node you are referring to:

https://github.com/comfyanonymous/ComfyUI

### Node Description and Use Case

这个可以提升细节

### Workflow Details (optional)

[sigmas分离采样.json](https://github.com/user-attachments/files/18235837/sigmas.json)

### Additional Context (optional)

Add any other context or information about the feature request here.

**Comment by ccssu** [comment]
@xiaobao9999 Thank you for the feedback. It has been supported and completed in PR: https://github.com/siliconflow/BizyAir/pull/293/files
