### ISSUE TITLE
[BUG] Kolors workflow error

### ISSUE THREAD

**Issue by Glenffi** [siliconflow/BizyAir#55]
### Describe the Bug

在云服务器部署ComfyUI，workflow如图
![345369ac4ba37f86eab27f3ad992851](https://github.com/user-attachments/assets/bb64c4ff-aa63-45cc-8248-ec394c42fa60)

### Steps to Reproduce

CPU服务器，4核16G RAM，python main.py --cpu --listen 0.0.0.0

### Environment

- **OS:** CentOS CentOS Stream 9 64位
- **Browser:** Chrome

###workflow
[workflow.json](https://github.com/user-attachments/files/16374470/workflow.json)

**Comment by doombeaker** [comment]
你好，我本地没有复现出问题：

![image](https://github.com/user-attachments/assets/fc17caed-10c4-41ee-babb-db8e54ae3c5c)

初步怀疑和那个输入的图片有关，你可以把那个输入的图片也提交一下吗。

**Comment by Glenffi** [comment]
不是的，输入图片我隐藏了，不会走到那两个节点。我在本地也可以跑通，只是在服务器上部署的会报错。

**Comment by doombeaker** [comment]
> 不是的，输入图片我隐藏了，不会走到那两个节点。我在本地也可以跑通，只是在服务器上部署的会报错。

是挂在 vae decoe 那个节点吗

**Comment by doombeaker** [comment]
> 不是的，输入图片我隐藏了，不会走到那两个节点。我在本地也可以跑通，只是在服务器上部署的会报错。

可能和 torch 的版本有关，可否将你服务器上 torch 版本，和你本地能跑通的 torch 版本升级成一致试试

**Comment by Glenffi** [comment]
是挂在vae decode，服务端上是cpu版本的torch，我看error是收到了不合法的msg呢？我以为是网络问题

**Comment by doombeaker** [comment]
> 是挂在vae decode，服务端上是cpu版本的torch，我看error是收到了不合法的msg呢？我以为是网络问题

可以看看你服务端的 ComfyUI 的日志，应该是中间某个地方抛异常了。

**Comment by Glenffi** [comment]
![image](https://github.com/user-attachments/assets/e0d70449-2d4e-48b5-ac70-d6de1b3da12d)
异常如图

**Comment by doombeaker** [comment]
麻烦提交一下你服务端上的 numpy 版本，初步确认少 numpy 版本不兼容的原因：
```
pip3 freeze|grep numpy
```

另外，可以尝试将服务端的 numpy 升级到这个版本，看看是否可以解决问题：

```
pip3 install numpy==1.24.4
```

**Comment by Glenffi** [comment]
已解决，感谢

**Comment by Glenffi** [comment]
我服务器上numpy版本是2.0.1，应该是安装comfyUI的时候自动装的
`pip3 install -r requirements.txt`
