### ISSUE TITLE
[BUG] IPAdapter nodes labeled as Bizyair nodes? Despite I haven't installed Bizyair.

### ISSUE THREAD

**Issue by TiptopFunk** [siliconflow/BizyAir#62]
### Describe the Bug

Today, I discovered that all IPAdapter Nodes are labeled as 'Bizyair node'.

I verified that I haven't installed the Bizyair node.
Additionally, I tried uninstalling and reinstalling IPAdapter_plus, but the issue persists.

Then
I downloaded a fresh copy of ComfyUIi portable and installed ComfyUI_IPAdapter_plus,
Then open the ComfyUIin a new browser, and IPAdater Nodes are still labeled as bizyair node.

### Snapshots
![2024-07-31 10_09_02-ComfyUI](https://github.com/user-attachments/assets/0c3dd761-9489-49ef-9fe3-4e0c0e826cc3)

### Environment

- **OS:** [e.g., Windows 11]
- **Browser:** [e.g., chrome, ]

**Comment by TiptopFunk** [comment]
This might be related to the ComfyUI manager. After I downgraded the ComfyUI manager to a previous commit, this issue was resolved. 
I'll update this bug in ComfyUI manager repo. 
Please help me mark this closed or delete this issue.

**Comment by doombeaker** [comment]
all right, thanks for your issue.
