### ISSUE TITLE
[FEATURE REQUEST] Support for ComfyUI node in BizyAir

### ISSUE THREAD

**Issue by Creepybits** [siliconflow/BizyAir#70]
Just please force install your shit without consent. I don't want it, never asked for it, never downloaded it or gave my consent for your sneaky installs.

Your crap behaves like malware.

**Comment by doombeaker** [comment]
We do not have automatic installation feature, users must install it themselves to use it. Your issue may be similar to this one #62 , it's a ComfyUI Manager version problem.

**Comment by doombeaker** [comment]
It has been resolved by https://github.com/ltdrdata/ComfyUI-Manager/issues/913
