### ISSUE TITLE
是否考虑适配Fooocus或SimpleSDXL?

### ISSUE THREAD

**Issue by Sheng991116** [siliconflow/BizyAir#84]
作者你好，我是在B站上了解到这个云节点。使用后，发现这套节点非常棒，可以让我在笔记本电脑上使用comfyui最新的节点和大部分功能。但是comfyui的门槛还是比较高，如果将该功能适配到Fooocus或SimpleSDXL，真正解决小白用户使用AI绘画的两个最大痛点：1、操作复杂；2、本地模型下载调试复杂。让用户真正专注到绘画本身。我想产品将会更有竞争力和影响力。不过这个产品，可能是另外一种形态了。在Fooocus或SimpleSDXL引入云节点，可能会形成不错的付费场景。愿意学习的用户使用本地模型和节点，愿意快速实现效果的用户使用云节点。一点小小想法。感谢此云节点的开发，帮助我学习了解Flux、可图模型。非常感谢！！！

**Comment by doombeaker** [comment]
谢谢你的肯定和建议。
近期不会考虑适配 ComfyUI 之外的框架，但是计划里如何降低普通用户安装 ComfyUI + BizyAir 的门槛（启动器、教程）。如果有这方面的建议，也欢迎交流，谢谢～
