### ISSUE TITLE
非常棒，要是llm那里能多个输入接口就好了，

### ISSUE THREAD

**Issue by gewei1986** [siliconflow/BizyAir#89]
要是llm那里能多个输入接口就好了，一个让视觉模型识别用户加载的图片，

**Comment by doombeaker** [comment]
谢谢你的建议，如果是想用 LLM 来处理视觉模型根据图片输出的 caption，
那有没有可能，多创建一个 SiliconCloud LLM API node，把 caption 作为输入，喂给 SiliconCloud LLM API node，也能达到目标？

欢迎交流～

**Comment by doombeaker** [comment]
> 正是因为 SiliconCloud LLM API node没有输入接口，所有没办法接受视觉模型的输出。我想的就是视觉模型输出图片描述，通过LLM模型来整理描述，制作成准确的PROMPT。😁

懂了，这个其实 comfyUI 本身就可以做到，将“widget转为输入的”，你可以在node 上点右键，然后选择 “convert widget to input”，就可以了。
推荐试试，很方便。
