### ISSUE TITLE
1536*1536的限制优化建议 Optimization suggestions for the 1536*1536 limit

### ISSUE THREAD

**Issue by 7enChan** [siliconflow/BizyAir#92]
很棒的项目，提个建议：
目前图片生成和图生图的流程都有宽*高 1536*1536 的限制，不知道是否可以改成总像素的限制，因为现在Flux支持最高200万像素，图片比例也不受限制。

Currently, both the image generation and image-to-image processes have a limitation of 1536*1536 in width and height. I wonder if it can be changed to a total pixel limit, as Flux currently supports up to 2 million pixels, and there are no restrictions on the aspect ratio.

**Comment by doombeaker** [comment]
谢谢你的建议。其实 1536x1536 是已经超过 200 万像素了。选择 1536 是因为它是 sdxl 时代，SAI 所推荐的高宽里的最大值。一般哪些设计场景，需要更高的宽高呢（我了解可能更高的像素，一般会考虑超分模型去扩图了）

**Comment by 7enChan** [comment]
> 谢谢你的建议。其实 1536x1536 是已经超过 200 万像素了。选择 1536 是因为它是 sdxl 时代，SAI 所推荐的高宽里的最大值。一般哪些设计场景，需要更高的宽高呢（我了解可能更高的像素，一般会考虑超分模型去扩图了）

感谢回复。

**Comment by 7enChan** [comment]
> 谢谢你的建议。其实 1536x1536 是已经超过 200 万像素了。选择 1536 是因为它是 sdxl 时代，SAI 所推荐的高宽里的最大值。一般哪些设计场景，需要更高的宽高呢（我了解可能更高的像素，一般会考虑超分模型去扩图了）

感谢回复。现在的像素数是足够使用的了，我的意思是调整限制宽高的方式，改为限制宽x高。
这样宽高比更自由也能充分利用像素，比如1080P也就是1920x1080是电影的一种高清格式，这时的像素其实是小于1536x1536的，但目前是没办法生成的。
Flux官方给出的样图宽或高很多也是超过1536的，但对应的高或宽就相对较小了，总像素并不会超过1536x1536.

**Comment by 7enChan** [comment]
不好意思，刚才试了下FLUX现在可以生成1920*1080的图片，不知道为啥之前遇到过一个超过1536的报错提示，可能是我搞错了
