### ISSUE TITLE
[BUG] VAEDecode  base64 

### ISSUE THREAD

**Issue by chenluyuZZ** [siliconflow/BizyAir#99]
![f4cc0cc44d71c8f590ed09f018a2b9f](https://github.com/user-attachments/assets/b5095ad2-ed5a-4366-9616-a04c9004a50f)
![9c61b1fbe2fa5893fe34daaae098c81](https://github.com/user-attachments/assets/fcd82aff-2082-4a7e-b124-5428111a197d)

**Comment by chenluyuZZ** [comment]
Official Vincennes chart sample error

**Comment by doombeaker** [comment]
please update your BizyAir to latest version
